-- ASK JORDAN CORE v1.0.0
-- مخصص لمشروع Supabase جديد ونظيف. شغّله مرة واحدة فقط.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  phone text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.ads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  category text not null,
  price numeric(12,2) not null default 0 check(price>=0),
  governorate text not null,
  area text not null default '',
  description text not null default '',
  phone text not null default '',
  status text not null default 'active' check(status in ('active','sold','deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ad_images (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists ads_status_created_idx on public.ads(status,created_at desc);
create index if not exists ads_user_idx on public.ads(user_id);
create index if not exists ads_search_idx on public.ads(governorate,category,price);

alter table public.profiles enable row level security;
alter table public.ads enable row level security;
alter table public.ad_images enable row level security;

create policy "profile owner read" on public.profiles for select using(auth.uid()=id);
create policy "profile owner update" on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id);
create policy "ads public read" on public.ads for select using(status='active' or auth.uid()=user_id);
create policy "ads owner insert" on public.ads for insert with check(auth.uid()=user_id);
create policy "ads owner update" on public.ads for update using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "images public read" on public.ad_images for select using(true);
create policy "images owner insert" on public.ad_images for insert with check(exists(select 1 from public.ads a where a.id=ad_id and a.user_id=auth.uid()));
create policy "images owner delete" on public.ad_images for delete using(exists(select 1 from public.ads a where a.id=ad_id and a.user_id=auth.uid()));

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,name,phone)
  values(new.id,coalesce(new.raw_user_meta_data->>'name',''),coalesce(new.raw_user_meta_data->>'phone',''))
  on conflict(id) do update set name=excluded.name,phone=excluded.phone;
  return new;
end;$$;

create trigger on_auth_user_created
after insert on auth.users for each row execute function public.handle_new_user();

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('ad-images','ad-images',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=true,file_size_limit=5242880,allowed_mime_types=array['image/jpeg','image/png','image/webp'];

create policy "public image read" on storage.objects for select using(bucket_id='ad-images');
create policy "user image upload" on storage.objects for insert to authenticated with check(bucket_id='ad-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "user image delete" on storage.objects for delete to authenticated using(bucket_id='ad-images' and (storage.foldername(name))[1]=auth.uid()::text);
