-- Ask Jordan v2.7.0 — Saved Searches & Matching Alerts
-- شغّل الملف مرة واحدة في Supabase SQL Editor.

create table if not exists public.saved_searches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  intent jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(user_id, query)
);

create index if not exists saved_searches_user_created_idx
  on public.saved_searches(user_id, created_at desc);

alter table public.saved_searches enable row level security;

drop policy if exists "saved searches owner read" on public.saved_searches;
create policy "saved searches owner read" on public.saved_searches
  for select using(auth.uid()=user_id);

drop policy if exists "saved searches owner insert" on public.saved_searches;
create policy "saved searches owner insert" on public.saved_searches
  for insert to authenticated with check(auth.uid()=user_id);

drop policy if exists "saved searches owner update" on public.saved_searches;
create policy "saved searches owner update" on public.saved_searches
  for update using(auth.uid()=user_id) with check(auth.uid()=user_id);

drop policy if exists "saved searches owner delete" on public.saved_searches;
create policy "saved searches owner delete" on public.saved_searches
  for delete using(auth.uid()=user_id);
