-- Ask Jordan v1.7.0 Admin Panel upgrade
-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor.

alter table public.profiles add column if not exists role text not null default 'user' check (role in ('user','admin'));

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  status text not null default 'open' check (status in ('open','reviewed','dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);

create index if not exists reports_status_created_idx on public.reports(status,created_at desc);
create index if not exists reports_ad_idx on public.reports(ad_id);
alter table public.reports enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path=public
as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin') $$;

-- تحديث سياسات الملفات الشخصية
 drop policy if exists "profile owner read" on public.profiles;
 create policy "profiles owner or admin read" on public.profiles for select using(auth.uid()=id or public.is_admin());
 drop policy if exists "profile owner update" on public.profiles;
 create policy "profile owner update" on public.profiles for update using(auth.uid()=id or public.is_admin()) with check(auth.uid()=id or public.is_admin());

-- تحديث سياسات الإعلانات للسماح للمشرف بالمراجعة
 drop policy if exists "ads public read" on public.ads;
 create policy "ads public owner admin read" on public.ads for select using(status='active' or auth.uid()=user_id or public.is_admin());
 drop policy if exists "ads owner update" on public.ads;
 create policy "ads owner or admin update" on public.ads for update using(auth.uid()=user_id or public.is_admin()) with check(auth.uid()=user_id or public.is_admin());

-- البلاغات
 drop policy if exists "reports authenticated insert" on public.reports;
 create policy "reports authenticated insert" on public.reports for insert to authenticated with check(auth.uid()=reporter_id);
 drop policy if exists "reports own or admin read" on public.reports;
 create policy "reports own or admin read" on public.reports for select using(auth.uid()=reporter_id or public.is_admin());
 drop policy if exists "reports admin update" on public.reports;
 create policy "reports admin update" on public.reports for update using(public.is_admin()) with check(public.is_admin());

-- مهم: استبدل الرقم برقم حسابك ثم شغّل السطر مرة واحدة لتصبح مشرفًا.
-- update public.profiles set role='admin' where phone='07XXXXXXXX';
