-- Ask Jordan v2.9.0 — In-App Notifications
-- شغّل الملف مرة واحدة في Supabase SQL Editor بعد ملفات v2.7 و v2.8.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('message','saved_search_match','system')),
  title text not null,
  body text,
  ad_id bigint references public.ads(id) on delete cascade,
  conversation_id bigint references public.conversations(id) on delete cascade,
  source_key text not null,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id, source_key)
);
create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id, read_at) where read_at is null;
alter table public.notifications enable row level security;
drop policy if exists "notifications owner read" on public.notifications;
create policy "notifications owner read" on public.notifications for select using(auth.uid()=user_id);
drop policy if exists "notifications owner update" on public.notifications;
create policy "notifications owner update" on public.notifications for update using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "notifications owner delete" on public.notifications;
create policy "notifications owner delete" on public.notifications for delete using(auth.uid()=user_id);

create or replace function public.notify_new_message() returns trigger language plpgsql security definer set search_path=public as $$
declare target_user uuid; ad_title text;
begin
  select case when c.buyer_id=new.sender_id then c.seller_id else c.buyer_id end, coalesce(a.title,'إعلان')
    into target_user,ad_title from public.conversations c left join public.ads a on a.id=c.ad_id where c.id=new.conversation_id;
  if target_user is not null then
    insert into public.notifications(user_id,type,title,body,ad_id,conversation_id,source_key)
    select target_user,'message','رسالة جديدة',left(new.body,180),c.ad_id,new.conversation_id,'message:'||new.id
    from public.conversations c where c.id=new.conversation_id
    on conflict(user_id,source_key) do nothing;
  end if;
  return new;
end $$;
drop trigger if exists trg_notify_new_message on public.messages;
create trigger trg_notify_new_message after insert on public.messages for each row execute function public.notify_new_message();

create or replace function public.notify_saved_search_matches() returns trigger language plpgsql security definer set search_path=public as $$
declare s record; i jsonb; matches boolean;
begin
  if new.status is distinct from 'active' then return new; end if;
  for s in select * from public.saved_searches where user_id<>new.user_id loop
    i:=coalesce(s.intent,'{}'::jsonb);
    matches:=true;
    if nullif(i->>'category','') is not null and lower(new.category)<>lower(i->>'category') then matches:=false; end if;
    if nullif(i->>'gov','') is not null and lower(new.governorate)<>lower(i->>'gov') then matches:=false; end if;
    if nullif(i->>'maxPrice','') is not null and coalesce(new.price,0)>0 and new.price>(i->>'maxPrice')::numeric then matches:=false; end if;
    if nullif(i->>'minPrice','') is not null and coalesce(new.price,0)<(i->>'minPrice')::numeric then matches:=false; end if;
    if matches then
      insert into public.notifications(user_id,type,title,body,ad_id,source_key)
      values(s.user_id,'saved_search_match','إعلان جديد يطابق بحثك',new.title||' · '||new.governorate,new.id,'saved-search:'||s.id||':ad:'||new.id)
      on conflict(user_id,source_key) do nothing;
    end if;
  end loop;
  return new;
end $$;
drop trigger if exists trg_notify_saved_search_matches on public.ads;
create trigger trg_notify_saved_search_matches after insert or update of status on public.ads for each row execute function public.notify_saved_search_matches();

-- إضافة الجداول إلى Realtime بأمان.
do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null;
end $$;

notify pgrst, 'reload schema';
