-- Ask Jordan v1.8.0 Growth & Monetization
-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor بعد v1.7.0.

alter table public.ads add column if not exists featured_until timestamptz;
create index if not exists ads_featured_until_idx on public.ads(featured_until desc);

create table if not exists public.platform_stats (
  id smallint primary key default 1 check (id=1),
  visits bigint not null default 0,
  searches bigint not null default 0,
  updated_at timestamptz not null default now()
);
insert into public.platform_stats(id) values(1) on conflict(id) do nothing;

create table if not exists public.promotion_requests (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan text not null check(plan in ('day','week','month')),
  amount numeric(10,2) not null check(amount>=0),
  status text not null default 'pending' check(status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);
create index if not exists promotion_requests_status_created_idx on public.promotion_requests(status,created_at desc);
create index if not exists promotion_requests_user_idx on public.promotion_requests(user_id,created_at desc);
alter table public.promotion_requests enable row level security;

create or replace function public.increment_site_visit()
returns bigint language plpgsql security definer set search_path=public as $$
declare n bigint;
begin
  update public.platform_stats set visits=visits+1,updated_at=now() where id=1 returning visits into n;
  return n;
end $$;

create or replace function public.increment_search_count()
returns bigint language plpgsql security definer set search_path=public as $$
declare n bigint;
begin
  update public.platform_stats set searches=searches+1,updated_at=now() where id=1 returning searches into n;
  return n;
end $$;

create or replace function public.get_public_stats()
returns table(visits bigint,searches bigint,users bigint,active_ads bigint)
language sql stable security definer set search_path=public as $$
  select s.visits,s.searches,
    (select count(*) from public.profiles),
    (select count(*) from public.ads where status='active')
  from public.platform_stats s where s.id=1
$$;

grant execute on function public.increment_site_visit() to anon,authenticated;
grant execute on function public.increment_search_count() to anon,authenticated;
grant execute on function public.get_public_stats() to anon,authenticated;

create policy "promotion owner insert" on public.promotion_requests for insert to authenticated with check(auth.uid()=user_id);
create policy "promotion owner or admin read" on public.promotion_requests for select using(auth.uid()=user_id or public.is_admin());
create policy "promotion admin update" on public.promotion_requests for update using(public.is_admin()) with check(public.is_admin());

-- رقم واتساب الدفع يُضبط داخل app.js في الثابت PAYMENT_PHONE.
