-- Ask Jordan v2.8.0: internal realtime conversations and messages
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  buyer_id uuid not null references auth.users(id) on delete cascade,
  seller_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  constraint conversations_different_users check (buyer_id <> seller_id),
  constraint conversations_unique unique (ad_id,buyer_id,seller_id)
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 1500),
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create index if not exists conversations_buyer_idx on public.conversations(buyer_id,last_message_at desc);
create index if not exists conversations_seller_idx on public.conversations(seller_id,last_message_at desc);
create index if not exists messages_conversation_idx on public.messages(conversation_id,created_at);
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
drop policy if exists conversations_select_participant on public.conversations;
create policy conversations_select_participant on public.conversations for select using (auth.uid()=buyer_id or auth.uid()=seller_id);
drop policy if exists conversations_update_participant on public.conversations;
create policy conversations_update_participant on public.conversations for update using (auth.uid()=buyer_id or auth.uid()=seller_id) with check (auth.uid()=buyer_id or auth.uid()=seller_id);
drop policy if exists messages_select_participant on public.messages;
create policy messages_select_participant on public.messages for select using (exists(select 1 from public.conversations c where c.id=conversation_id and auth.uid() in (c.buyer_id,c.seller_id)));
drop policy if exists messages_insert_participant on public.messages;
create policy messages_insert_participant on public.messages for insert with check (sender_id=auth.uid() and exists(select 1 from public.conversations c where c.id=conversation_id and auth.uid() in (c.buyer_id,c.seller_id)));
drop policy if exists messages_update_participant on public.messages;
create policy messages_update_participant on public.messages for update using (exists(select 1 from public.conversations c where c.id=conversation_id and auth.uid() in (c.buyer_id,c.seller_id))) with check (exists(select 1 from public.conversations c where c.id=conversation_id and auth.uid() in (c.buyer_id,c.seller_id)));
create or replace function public.get_or_create_conversation(p_ad_id bigint) returns bigint language plpgsql security definer set search_path=public as $$
declare v_seller uuid;v_id bigint;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول';end if;
  select user_id into v_seller from public.ads where id=p_ad_id and status='active';
  if v_seller is null then raise exception 'الإعلان غير متاح';end if;
  if v_seller=auth.uid() then raise exception 'لا يمكنك مراسلة نفسك';end if;
  insert into public.conversations(ad_id,buyer_id,seller_id) values(p_ad_id,auth.uid(),v_seller)
  on conflict(ad_id,buyer_id,seller_id) do update set last_message_at=public.conversations.last_message_at returning id into v_id;
  return v_id;
end $$;
grant execute on function public.get_or_create_conversation(bigint) to authenticated;
do $$ begin alter publication supabase_realtime add table public.messages; exception when duplicate_object then null; end $$;
