-- Ask Jordan v3.3.0 — AI Fraud Detection, Duplicate Detection & Trust Score
begin;

alter table public.ads drop constraint if exists ads_status_check;
alter table public.ads add constraint ads_status_check check (status in ('active','sold','deleted','under_review','rejected'));
alter table public.ads add column if not exists trust_score integer not null default 100 check (trust_score between 0 and 100);
alter table public.ads add column if not exists risk_score integer not null default 0 check (risk_score between 0 and 100);
alter table public.ads add column if not exists moderation_status text not null default 'approved' check (moderation_status in ('approved','pending','rejected'));
alter table public.ads add column if not exists moderation_reasons jsonb not null default '[]'::jsonb;
alter table public.ads add column if not exists duplicate_of bigint references public.ads(id) on delete set null;
alter table public.ads add column if not exists duplicate_score integer not null default 0 check (duplicate_score between 0 and 100);

create table if not exists public.ad_moderation_reviews (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  risk_score integer not null default 0 check (risk_score between 0 and 100),
  trust_score integer not null default 100 check (trust_score between 0 and 100),
  risk_level text not null default 'منخفض',
  action text not null default 'allow' check (action in ('allow','review','block')),
  reasons jsonb not null default '[]'::jsonb,
  duplicate_of bigint references public.ads(id) on delete set null,
  duplicate_score integer not null default 0 check (duplicate_score between 0 and 100),
  review_status text not null default 'pending' check (review_status in ('pending','approved','rejected')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists moderation_pending_idx on public.ad_moderation_reviews(review_status,created_at desc);
alter table public.ad_moderation_reviews enable row level security;

drop policy if exists "moderation owner read" on public.ad_moderation_reviews;
create policy "moderation owner read" on public.ad_moderation_reviews for select using(auth.uid()=user_id or public.is_admin());
drop policy if exists "moderation owner insert" on public.ad_moderation_reviews;
create policy "moderation owner insert" on public.ad_moderation_reviews for insert with check(auth.uid()=user_id);
drop policy if exists "moderation admin update" on public.ad_moderation_reviews;
create policy "moderation admin update" on public.ad_moderation_reviews for update using(public.is_admin()) with check(public.is_admin());

commit;
